[package]
name = "zylith_settlement_statement"
version = "0.1.0"
edition = "2024_07"

[lib]
sierra = true

[[target.executable]]
function = "zylith_settlement_statement::executable::main"

[cairo]
enable-gas = false

[dependencies]
cairo_execute = ">=2.16.1"

[dev-dependencies]
cairo_test = "2.17.0"
