[package]
name = "zylith_settlement_statement"
version = "0.1.0"
edition = "2024_07"

[lib]
sierra = true

[[target.executable]]
function = "zylith_settlement_statement::executable::main"

[cairo]
enable-gas = false

[profile.snforge.cairo]
enable-gas = true

[dependencies]
cairo_execute = "=2.18.0"

[dev-dependencies]
cairo_test = "=2.18.0"
snforge_std = "=0.61.0"
